package root:component;

world root {
  import component:test-package/env;

  export main: func(x: string) -> string;
}
package component:test-package {
  interface env {
    reverse-string: func(s: string) -> string;
  }
}
