// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type DataPayload = component::test_package::env::DataPayload;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(
    arg0: i32,
    arg1: *mut u8,
    arg2: *mut u8,
    arg3: ::core::mem::MaybeUninit<u64>,
    arg4: *mut u8,
    arg5: *mut u8,
    arg6: *mut u8,
    arg7: *mut u8,
    arg8: *mut u8,
    arg9: *mut u8,
    arg10: *mut u8,
    arg11: usize,
    arg12: *mut u8,
    arg13: usize,
    arg14: *mut u8,
    arg15: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    use component::test_package::env::DataPayload as V20;
    let v20 = match arg0 {
        0 => {
            let e20 = {
                let len0 = arg2 as usize;
                let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                let base4 = arg4;
                let len4 = arg5 as usize;
                let mut result4 = _rt::Vec::with_capacity(len4);
                for i in 0..len4 {
                    let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                    let e4 = {
                        let l1 = *base.add(0).cast::<*mut u8>();
                        let l2 = *base
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len3 = l2;
                        let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                        _rt::string_lift(bytes3)
                    };
                    result4.push(e4);
                }
                _rt::cabi_dealloc(
                    base4,
                    len4 * (2 * ::core::mem::size_of::<*const u8>()),
                    ::core::mem::size_of::<*const u8>(),
                );
                let len5 = arg7 as usize;
                let bytes5 = _rt::Vec::from_raw_parts(arg6.cast(), len5, len5);
                let len6 = arg9 as usize;
                let bytes6 = _rt::Vec::from_raw_parts(arg8.cast(), len6, len6);
                let len7 = arg11;
                let bytes7 = _rt::Vec::from_raw_parts(arg10.cast(), len7, len7);
                let len8 = arg13;
                let bytes8 = _rt::Vec::from_raw_parts(arg12.cast(), len8, len8);
                let len9 = arg15;
                let bytes9 = _rt::Vec::from_raw_parts(arg14.cast(), len9, len9);
                component::test_package::env::OrderInfo {
                    order_id: _rt::string_lift(bytes0),
                    total_amount: f64::from_bits(arg3.assume_init() as i64 as u64),
                    items: result4,
                    shipping_address: component::test_package::env::Address {
                        street: _rt::string_lift(bytes5),
                        city: _rt::string_lift(bytes6),
                        state: _rt::string_lift(bytes7),
                        country: _rt::string_lift(bytes8),
                        postal_code: _rt::string_lift(bytes9),
                    },
                }
            };
            V20::Order(e20)
        }
        1 => {
            let e20 = {
                let len10 = arg2 as usize;
                let bytes10 = _rt::Vec::from_raw_parts(arg1.cast(), len10, len10);
                let len11 = arg4 as usize;
                let bytes11 = _rt::Vec::from_raw_parts(
                    arg3.as_ptr().cast::<*mut u8>().read().cast(),
                    len11,
                    len11,
                );
                let len12 = arg6 as usize;
                let bytes12 = _rt::Vec::from_raw_parts(arg5.cast(), len12, len12);
                let len13 = arg8 as usize;
                let bytes13 = _rt::Vec::from_raw_parts(arg7.cast(), len13, len13);
                let len14 = arg10 as usize;
                let bytes14 = _rt::Vec::from_raw_parts(arg9.cast(), len14, len14);
                component::test_package::env::Address {
                    street: _rt::string_lift(bytes10),
                    city: _rt::string_lift(bytes11),
                    state: _rt::string_lift(bytes12),
                    country: _rt::string_lift(bytes13),
                    postal_code: _rt::string_lift(bytes14),
                }
            };
            V20::AddressUpdate(e20)
        }
        2 => {
            let e20 = {
                let len15 = arg2 as usize;
                let bytes15 = _rt::Vec::from_raw_parts(arg1.cast(), len15, len15);
                _rt::string_lift(bytes15)
            };
            V20::SimpleMessage(e20)
        }
        3 => {
            let e20 = {
                let len16 = arg2 as usize;
                _rt::Vec::from_raw_parts(arg1.cast(), len16, len16)
            };
            V20::NumericData(e20)
        }
        n => {
            debug_assert_eq!(n, 4, "invalid enum discriminant");
            let e20 = {
                use component::test_package::env::PaymentMethod as V19;
                let v19 = match arg1 as i32 {
                    0 => {
                        let e19 = {
                            let len17 = arg3.assume_init() as i64 as usize;
                            let bytes17 = _rt::Vec::from_raw_parts(
                                arg2.cast(),
                                len17,
                                len17,
                            );
                            _rt::string_lift(bytes17)
                        };
                        V19::CreditCard(e19)
                    }
                    1 => {
                        let e19 = {
                            let len18 = arg3.assume_init() as i64 as usize;
                            let bytes18 = _rt::Vec::from_raw_parts(
                                arg2.cast(),
                                len18,
                                len18,
                            );
                            _rt::string_lift(bytes18)
                        };
                        V19::Paypal(e19)
                    }
                    2 => V19::BankTransfer,
                    n => {
                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                        V19::Cash
                    }
                };
                v19
            };
            V20::Payment(e20)
        }
    };
    let result21 = T::main(v20);
    let ptr22 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec23 = (result21.into_bytes()).into_boxed_slice();
    let ptr23 = vec23.as_ptr().cast::<u8>();
    let len23 = vec23.len();
    ::core::mem::forget(vec23);
    *ptr22.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len23;
    *ptr22.add(0).cast::<*mut u8>() = ptr23.cast_mut();
    ptr22
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_main<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn main(data: DataPayload) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : i32, arg1 : * mut u8, arg2 : * mut u8, arg3 :
        ::core::mem::MaybeUninit::< u64 >, arg4 : * mut u8, arg5 : * mut u8, arg6 : * mut
        u8, arg7 : * mut u8, arg8 : * mut u8, arg9 : * mut u8, arg10 : * mut u8, arg11 :
        usize, arg12 : * mut u8, arg13 : usize, arg14 : * mut u8, arg15 : usize,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_main_cabi::<$ty > (arg0, arg1,
        arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13,
        arg14, arg15) } } #[unsafe (export_name = "cabi_post_main")] unsafe extern "C" fn
        _post_return_main(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_main::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod test_package {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Nested record for address
            #[derive(Clone)]
            pub struct Address {
                pub street: _rt::String,
                pub city: _rt::String,
                pub state: _rt::String,
                pub country: _rt::String,
                pub postal_code: _rt::String,
            }
            impl ::core::fmt::Debug for Address {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Address")
                        .field("street", &self.street)
                        .field("city", &self.city)
                        .field("state", &self.state)
                        .field("country", &self.country)
                        .field("postal-code", &self.postal_code)
                        .finish()
                }
            }
            /// Record with nested types
            #[derive(Clone)]
            pub struct OrderInfo {
                pub order_id: _rt::String,
                pub total_amount: f64,
                pub items: _rt::Vec<_rt::String>,
                pub shipping_address: Address,
            }
            impl ::core::fmt::Debug for OrderInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("OrderInfo")
                        .field("order-id", &self.order_id)
                        .field("total-amount", &self.total_amount)
                        .field("items", &self.items)
                        .field("shipping-address", &self.shipping_address)
                        .finish()
                }
            }
            /// Nested variant
            #[derive(Clone)]
            pub enum PaymentMethod {
                CreditCard(_rt::String),
                Paypal(_rt::String),
                BankTransfer,
                Cash,
            }
            impl ::core::fmt::Debug for PaymentMethod {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PaymentMethod::CreditCard(e) => {
                            f.debug_tuple("PaymentMethod::CreditCard").field(e).finish()
                        }
                        PaymentMethod::Paypal(e) => {
                            f.debug_tuple("PaymentMethod::Paypal").field(e).finish()
                        }
                        PaymentMethod::BankTransfer => {
                            f.debug_tuple("PaymentMethod::BankTransfer").finish()
                        }
                        PaymentMethod::Cash => {
                            f.debug_tuple("PaymentMethod::Cash").finish()
                        }
                    }
                }
            }
            /// Main variant with various types and nesting
            #[derive(Clone)]
            pub enum DataPayload {
                Order(OrderInfo),
                AddressUpdate(Address),
                SimpleMessage(_rt::String),
                NumericData(_rt::Vec<i64>),
                Payment(PaymentMethod),
            }
            impl ::core::fmt::Debug for DataPayload {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        DataPayload::Order(e) => {
                            f.debug_tuple("DataPayload::Order").field(e).finish()
                        }
                        DataPayload::AddressUpdate(e) => {
                            f.debug_tuple("DataPayload::AddressUpdate").field(e).finish()
                        }
                        DataPayload::SimpleMessage(e) => {
                            f.debug_tuple("DataPayload::SimpleMessage").field(e).finish()
                        }
                        DataPayload::NumericData(e) => {
                            f.debug_tuple("DataPayload::NumericData").field(e).finish()
                        }
                        DataPayload::Payment(e) => {
                            f.debug_tuple("DataPayload::Payment").field(e).finish()
                        }
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Import function that processes the variant
            pub fn process_data(input: &DataPayload) -> DataPayload {
                unsafe {
                    let mut cleanup_list = _rt::Vec::new();
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 16 + 14 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 16
                            + 14 * ::core::mem::size_of::<*const u8>()],
                    );
                    let (
                        result21_0,
                        result21_1,
                        result21_2,
                        result21_3,
                        result21_4,
                        result21_5,
                        result21_6,
                        result21_7,
                        result21_8,
                        result21_9,
                        result21_10,
                        result21_11,
                        result21_12,
                        result21_13,
                        result21_14,
                        result21_15,
                    ) = match input {
                        DataPayload::Order(e) => {
                            let OrderInfo {
                                order_id: order_id0,
                                total_amount: total_amount0,
                                items: items0,
                                shipping_address: shipping_address0,
                            } = e;
                            let vec1 = order_id0;
                            let ptr1 = vec1.as_ptr().cast::<u8>();
                            let len1 = vec1.len();
                            let vec3 = items0;
                            let len3 = vec3.len();
                            let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result3 = if layout3.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout3);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec3.into_iter().enumerate() {
                                let base = result3
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec2 = e;
                                    let ptr2 = vec2.as_ptr().cast::<u8>();
                                    let len2 = vec2.len();
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len2;
                                    *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                                }
                            }
                            let Address {
                                street: street4,
                                city: city4,
                                state: state4,
                                country: country4,
                                postal_code: postal_code4,
                            } = shipping_address0;
                            let vec5 = street4;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            let vec6 = city4;
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            let vec7 = state4;
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            let vec8 = country4;
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            let vec9 = postal_code4;
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            cleanup_list.extend_from_slice(&[(result3, layout3)]);
                            (
                                0i32,
                                ptr1.cast_mut(),
                                len1 as *mut u8,
                                ::core::mem::MaybeUninit::new(
                                    (_rt::as_f64(total_amount0)).to_bits() as i64 as u64,
                                ),
                                result3,
                                len3 as *mut u8,
                                ptr5.cast_mut(),
                                len5 as *mut u8,
                                ptr6.cast_mut(),
                                len6 as *mut u8,
                                ptr7.cast_mut(),
                                len7,
                                ptr8.cast_mut(),
                                len8,
                                ptr9.cast_mut(),
                                len9,
                            )
                        }
                        DataPayload::AddressUpdate(e) => {
                            let Address {
                                street: street10,
                                city: city10,
                                state: state10,
                                country: country10,
                                postal_code: postal_code10,
                            } = e;
                            let vec11 = street10;
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            let vec12 = city10;
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            let vec13 = state10;
                            let ptr13 = vec13.as_ptr().cast::<u8>();
                            let len13 = vec13.len();
                            let vec14 = country10;
                            let ptr14 = vec14.as_ptr().cast::<u8>();
                            let len14 = vec14.len();
                            let vec15 = postal_code10;
                            let ptr15 = vec15.as_ptr().cast::<u8>();
                            let len15 = vec15.len();
                            (
                                1i32,
                                ptr11.cast_mut(),
                                len11 as *mut u8,
                                {
                                    let mut t = ::core::mem::MaybeUninit::<u64>::uninit();
                                    t.as_mut_ptr().cast::<*mut u8>().write(ptr12.cast_mut());
                                    t
                                },
                                len12 as *mut u8,
                                ptr13.cast_mut(),
                                len13 as *mut u8,
                                ptr14.cast_mut(),
                                len14 as *mut u8,
                                ptr15.cast_mut(),
                                len15 as *mut u8,
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                            )
                        }
                        DataPayload::SimpleMessage(e) => {
                            let vec16 = e;
                            let ptr16 = vec16.as_ptr().cast::<u8>();
                            let len16 = vec16.len();
                            (
                                2i32,
                                ptr16.cast_mut(),
                                len16 as *mut u8,
                                ::core::mem::MaybeUninit::<u64>::zeroed(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                            )
                        }
                        DataPayload::NumericData(e) => {
                            let vec17 = e;
                            let ptr17 = vec17.as_ptr().cast::<u8>();
                            let len17 = vec17.len();
                            (
                                3i32,
                                ptr17.cast_mut(),
                                len17 as *mut u8,
                                ::core::mem::MaybeUninit::<u64>::zeroed(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                            )
                        }
                        DataPayload::Payment(e) => {
                            let (result20_0, result20_1, result20_2) = match e {
                                PaymentMethod::CreditCard(e) => {
                                    let vec18 = e;
                                    let ptr18 = vec18.as_ptr().cast::<u8>();
                                    let len18 = vec18.len();
                                    (0i32, ptr18.cast_mut(), len18)
                                }
                                PaymentMethod::Paypal(e) => {
                                    let vec19 = e;
                                    let ptr19 = vec19.as_ptr().cast::<u8>();
                                    let len19 = vec19.len();
                                    (1i32, ptr19.cast_mut(), len19)
                                }
                                PaymentMethod::BankTransfer => {
                                    (2i32, ::core::ptr::null_mut(), 0usize)
                                }
                                PaymentMethod::Cash => {
                                    (3i32, ::core::ptr::null_mut(), 0usize)
                                }
                            };
                            (
                                4i32,
                                result20_0 as *mut u8,
                                result20_1,
                                ::core::mem::MaybeUninit::new(result20_2 as i64 as u64),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                                ::core::ptr::null_mut(),
                                0usize,
                            )
                        }
                    };
                    let ptr22 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "component:test-package/env")]
                    unsafe extern "C" {
                        #[link_name = "process-data"]
                        fn wit_import23(
                            _: i32,
                            _: *mut u8,
                            _: *mut u8,
                            _: ::core::mem::MaybeUninit<u64>,
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import23(
                        _: i32,
                        _: *mut u8,
                        _: *mut u8,
                        _: ::core::mem::MaybeUninit<u64>,
                        _: *mut u8,
                        _: *mut u8,
                        _: *mut u8,
                        _: *mut u8,
                        _: *mut u8,
                        _: *mut u8,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import23(
                            result21_0,
                            result21_1,
                            result21_2,
                            result21_3,
                            result21_4,
                            result21_5,
                            result21_6,
                            result21_7,
                            result21_8,
                            result21_9,
                            result21_10,
                            result21_11,
                            result21_12,
                            result21_13,
                            result21_14,
                            result21_15,
                            ptr22,
                        )
                    };
                    let l24 = i32::from(*ptr22.add(0).cast::<u8>());
                    let v79 = match l24 {
                        0 => {
                            let e79 = {
                                let l25 = *ptr22.add(8).cast::<*mut u8>();
                                let l26 = *ptr22
                                    .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len27 = l26;
                                let bytes27 = _rt::Vec::from_raw_parts(
                                    l25.cast(),
                                    len27,
                                    len27,
                                );
                                let l28 = *ptr22
                                    .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<f64>();
                                let l29 = *ptr22
                                    .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l30 = *ptr22
                                    .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base34 = l29;
                                let len34 = l30;
                                let mut result34 = _rt::Vec::with_capacity(len34);
                                for i in 0..len34 {
                                    let base = base34
                                        .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                    let e34 = {
                                        let l31 = *base.add(0).cast::<*mut u8>();
                                        let l32 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len33 = l32;
                                        let bytes33 = _rt::Vec::from_raw_parts(
                                            l31.cast(),
                                            len33,
                                            len33,
                                        );
                                        _rt::string_lift(bytes33)
                                    };
                                    result34.push(e34);
                                }
                                _rt::cabi_dealloc(
                                    base34,
                                    len34 * (2 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                let l35 = *ptr22
                                    .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l36 = *ptr22
                                    .add(16 + 5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len37 = l36;
                                let bytes37 = _rt::Vec::from_raw_parts(
                                    l35.cast(),
                                    len37,
                                    len37,
                                );
                                let l38 = *ptr22
                                    .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l39 = *ptr22
                                    .add(16 + 7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len40 = l39;
                                let bytes40 = _rt::Vec::from_raw_parts(
                                    l38.cast(),
                                    len40,
                                    len40,
                                );
                                let l41 = *ptr22
                                    .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l42 = *ptr22
                                    .add(16 + 9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len43 = l42;
                                let bytes43 = _rt::Vec::from_raw_parts(
                                    l41.cast(),
                                    len43,
                                    len43,
                                );
                                let l44 = *ptr22
                                    .add(16 + 10 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l45 = *ptr22
                                    .add(16 + 11 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len46 = l45;
                                let bytes46 = _rt::Vec::from_raw_parts(
                                    l44.cast(),
                                    len46,
                                    len46,
                                );
                                let l47 = *ptr22
                                    .add(16 + 12 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l48 = *ptr22
                                    .add(16 + 13 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len49 = l48;
                                let bytes49 = _rt::Vec::from_raw_parts(
                                    l47.cast(),
                                    len49,
                                    len49,
                                );
                                OrderInfo {
                                    order_id: _rt::string_lift(bytes27),
                                    total_amount: l28,
                                    items: result34,
                                    shipping_address: Address {
                                        street: _rt::string_lift(bytes37),
                                        city: _rt::string_lift(bytes40),
                                        state: _rt::string_lift(bytes43),
                                        country: _rt::string_lift(bytes46),
                                        postal_code: _rt::string_lift(bytes49),
                                    },
                                }
                            };
                            DataPayload::Order(e79)
                        }
                        1 => {
                            let e79 = {
                                let l50 = *ptr22.add(8).cast::<*mut u8>();
                                let l51 = *ptr22
                                    .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len52 = l51;
                                let bytes52 = _rt::Vec::from_raw_parts(
                                    l50.cast(),
                                    len52,
                                    len52,
                                );
                                let l53 = *ptr22
                                    .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l54 = *ptr22
                                    .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len55 = l54;
                                let bytes55 = _rt::Vec::from_raw_parts(
                                    l53.cast(),
                                    len55,
                                    len55,
                                );
                                let l56 = *ptr22
                                    .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l57 = *ptr22
                                    .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len58 = l57;
                                let bytes58 = _rt::Vec::from_raw_parts(
                                    l56.cast(),
                                    len58,
                                    len58,
                                );
                                let l59 = *ptr22
                                    .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l60 = *ptr22
                                    .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len61 = l60;
                                let bytes61 = _rt::Vec::from_raw_parts(
                                    l59.cast(),
                                    len61,
                                    len61,
                                );
                                let l62 = *ptr22
                                    .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l63 = *ptr22
                                    .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len64 = l63;
                                let bytes64 = _rt::Vec::from_raw_parts(
                                    l62.cast(),
                                    len64,
                                    len64,
                                );
                                Address {
                                    street: _rt::string_lift(bytes52),
                                    city: _rt::string_lift(bytes55),
                                    state: _rt::string_lift(bytes58),
                                    country: _rt::string_lift(bytes61),
                                    postal_code: _rt::string_lift(bytes64),
                                }
                            };
                            DataPayload::AddressUpdate(e79)
                        }
                        2 => {
                            let e79 = {
                                let l65 = *ptr22.add(8).cast::<*mut u8>();
                                let l66 = *ptr22
                                    .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len67 = l66;
                                let bytes67 = _rt::Vec::from_raw_parts(
                                    l65.cast(),
                                    len67,
                                    len67,
                                );
                                _rt::string_lift(bytes67)
                            };
                            DataPayload::SimpleMessage(e79)
                        }
                        3 => {
                            let e79 = {
                                let l68 = *ptr22.add(8).cast::<*mut u8>();
                                let l69 = *ptr22
                                    .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len70 = l69;
                                _rt::Vec::from_raw_parts(l68.cast(), len70, len70)
                            };
                            DataPayload::NumericData(e79)
                        }
                        n => {
                            debug_assert_eq!(n, 4, "invalid enum discriminant");
                            let e79 = {
                                let l71 = i32::from(*ptr22.add(8).cast::<u8>());
                                let v78 = match l71 {
                                    0 => {
                                        let e78 = {
                                            let l72 = *ptr22
                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l73 = *ptr22
                                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len74 = l73;
                                            let bytes74 = _rt::Vec::from_raw_parts(
                                                l72.cast(),
                                                len74,
                                                len74,
                                            );
                                            _rt::string_lift(bytes74)
                                        };
                                        PaymentMethod::CreditCard(e78)
                                    }
                                    1 => {
                                        let e78 = {
                                            let l75 = *ptr22
                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l76 = *ptr22
                                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len77 = l76;
                                            let bytes77 = _rt::Vec::from_raw_parts(
                                                l75.cast(),
                                                len77,
                                                len77,
                                            );
                                            _rt::string_lift(bytes77)
                                        };
                                        PaymentMethod::Paypal(e78)
                                    }
                                    2 => PaymentMethod::BankTransfer,
                                    n => {
                                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                                        PaymentMethod::Cash
                                    }
                                };
                                v78
                            };
                            DataPayload::Payment(e79)
                        }
                    };
                    let result80 = v79;
                    for (ptr, layout) in cleanup_list {
                        if layout.size() != 0 {
                            _rt::alloc::dealloc(ptr.cast(), layout);
                        }
                    }
                    result80
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:test-package:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 584] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc9\x03\x01A\x02\x01\
A\x06\x01B\x0c\x01r\x05\x06streets\x04citys\x05states\x07countrys\x0bpostal-code\
s\x04\0\x07address\x03\0\0\x01ps\x01r\x04\x08order-ids\x0ctotal-amountu\x05items\
\x02\x10shipping-address\x01\x04\0\x0aorder-info\x03\0\x03\x01q\x04\x0bcredit-ca\
rd\x01s\0\x06paypal\x01s\0\x0dbank-transfer\0\0\x04cash\0\0\x04\0\x0epayment-met\
hod\x03\0\x05\x01px\x01q\x05\x05order\x01\x04\0\x0eaddress-update\x01\x01\0\x0es\
imple-message\x01s\0\x0cnumeric-data\x01\x07\0\x07payment\x01\x06\0\x04\0\x0cdat\
a-payload\x03\0\x08\x01@\x01\x05input\x09\0\x09\x04\0\x0cprocess-data\x01\x0a\x03\
\0\x1acomponent:test-package/env\x05\0\x02\x03\0\0\x0cdata-payload\x03\0\x0cdata\
-payload\x03\0\x01\x01@\x01\x04data\x02\0s\x04\0\x04main\x01\x03\x04\0\x1fcompon\
ent:test-package/my-world\x04\0\x0b\x0e\x01\0\x08my-world\x03\0\0\0G\x09producer\
s\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.4\
1.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
