// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type UserProfile = component::test_package::env::UserProfile;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(
    arg0: i64,
    arg1: *mut u8,
    arg2: usize,
    arg3: *mut u8,
    arg4: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg2;
    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
    let base4 = arg3;
    let len4 = arg4;
    let mut result4 = _rt::Vec::with_capacity(len4);
    for i in 0..len4 {
        let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        let e4 = {
            let l1 = *base.add(0).cast::<*mut u8>();
            let l2 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len3 = l2;
            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
            _rt::string_lift(bytes3)
        };
        result4.push(e4);
    }
    _rt::cabi_dealloc(
        base4,
        len4 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result5 = T::main(component::test_package::env::UserProfile {
        id: arg0 as u64,
        username: _rt::string_lift(bytes0),
        tags: result4,
    });
    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec7 = (result5.into_bytes()).into_boxed_slice();
    let ptr7 = vec7.as_ptr().cast::<u8>();
    let len7 = vec7.len();
    ::core::mem::forget(vec7);
    *ptr6.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
    *ptr6.add(0).cast::<*mut u8>() = ptr7.cast_mut();
    ptr6
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_main<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn main(profile: UserProfile) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : i64, arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*:: _export_main_cabi::<$ty >
        (arg0, arg1, arg2, arg3, arg4) } } #[unsafe (export_name = "cabi_post_main")]
        unsafe extern "C" fn _post_return_main(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_main::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod test_package {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct UserProfile {
                pub id: u64,
                pub username: _rt::String,
                pub tags: _rt::Vec<_rt::String>,
            }
            impl ::core::fmt::Debug for UserProfile {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("UserProfile")
                        .field("id", &self.id)
                        .field("username", &self.username)
                        .field("tags", &self.tags)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn process_profile(profile: &UserProfile) -> UserProfile {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 8 + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 8
                            + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let UserProfile { id: id0, username: username0, tags: tags0 } = profile;
                    let vec1 = username0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec3 = tags0;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec2 = e;
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    }
                    let ptr4 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "component:test-package/env")]
                    unsafe extern "C" {
                        #[link_name = "process-profile"]
                        fn wit_import5(
                            _: i64,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import5(
                        _: i64,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import5(
                            _rt::as_i64(id0),
                            ptr1.cast_mut(),
                            len1,
                            result3,
                            len3,
                            ptr4,
                        )
                    };
                    let l6 = *ptr4.add(0).cast::<i64>();
                    let l7 = *ptr4.add(8).cast::<*mut u8>();
                    let l8 = *ptr4
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len9 = l8;
                    let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                    let l10 = *ptr4
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l11 = *ptr4
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base15 = l10;
                    let len15 = l11;
                    let mut result15 = _rt::Vec::with_capacity(len15);
                    for i in 0..len15 {
                        let base = base15
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e15 = {
                            let l12 = *base.add(0).cast::<*mut u8>();
                            let l13 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            _rt::string_lift(bytes14)
                        };
                        result15.push(e15);
                    }
                    _rt::cabi_dealloc(
                        base15,
                        len15 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result16 = UserProfile {
                        id: l6 as u64,
                        username: _rt::string_lift(bytes9),
                        tags: result15,
                    };
                    if layout3.size() != 0 {
                        _rt::alloc::dealloc(result3.cast(), layout3);
                    }
                    result16
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:test-package:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 339] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd4\x01\x01A\x02\x01\
A\x06\x01B\x05\x01ps\x01r\x03\x02idw\x08usernames\x04tags\0\x04\0\x0cuser-profil\
e\x03\0\x01\x01@\x01\x07profile\x02\0\x02\x04\0\x0fprocess-profile\x01\x03\x03\0\
\x1acomponent:test-package/env\x05\0\x02\x03\0\0\x0cuser-profile\x03\0\x0cuser-p\
rofile\x03\0\x01\x01@\x01\x07profile\x02\0s\x04\0\x04main\x01\x03\x04\0\x1fcompo\
nent:test-package/my-world\x04\0\x0b\x0e\x01\0\x08my-world\x03\0\0\0G\x09produce\
rs\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.\
41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
