[package]
name = "wasi-modules"
edition = "2024"

[[bin]]
name = "wasi-compressor"
path = "compressor.rs"

[dependencies]
anyhow = "1.0.98"
clap = { workspace = true, features = ["derive"] }
walkdir = "2.5.0"
zstd = "0.13.3"


