// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type PotRecord = component::test_package::env::PotRecord;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(
    arg0: i64,
    arg1: *mut u8,
    arg2: usize,
    arg3: i32,
    arg4: f32,
    arg5: i32,
    arg6: *mut u8,
    arg7: usize,
    arg8: i32,
    arg9: *mut u8,
    arg10: ::core::mem::MaybeUninit<u64>,
    arg11: usize,
    arg12: i32,
    arg13: *mut u8,
    arg14: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg2;
    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
    use component::test_package::env::PotPayload as V10;
    let v10 = match arg8 {
        0 => {
            let e10 = {
                let len5 = arg10.assume_init() as i64 as usize;
                _rt::Vec::from_raw_parts(arg9.cast(), len5, len5)
            };
            V10::Numbers(e10)
        }
        1 => {
            let e10 = component::test_package::env::SmallRecord {
                count: arg9 as i32 as u32,
                ratio: f64::from_bits(arg10.assume_init() as i64 as u64),
            };
            V10::Small(e10)
        }
        2 => {
            let e10 = {
                use component::test_package::env::PaymentMethod as V8;
                let v8 = match arg9 as i32 {
                    0 => {
                        let e8 = {
                            let len6 = arg11;
                            let bytes6 = _rt::Vec::from_raw_parts(
                                arg10.as_ptr().cast::<*mut u8>().read().cast(),
                                len6,
                                len6,
                            );
                            _rt::string_lift(bytes6)
                        };
                        V8::CreditCard(e8)
                    }
                    1 => {
                        let e8 = {
                            let len7 = arg11;
                            let bytes7 = _rt::Vec::from_raw_parts(
                                arg10.as_ptr().cast::<*mut u8>().read().cast(),
                                len7,
                                len7,
                            );
                            _rt::string_lift(bytes7)
                        };
                        V8::Paypal(e8)
                    }
                    n => {
                        debug_assert_eq!(n, 2, "invalid enum discriminant");
                        V8::Cash
                    }
                };
                v8
            };
            V10::Payment(e10)
        }
        n => {
            debug_assert_eq!(n, 3, "invalid enum discriminant");
            let e10 = {
                let len9 = arg10.assume_init() as i64 as usize;
                let bytes9 = _rt::Vec::from_raw_parts(arg9.cast(), len9, len9);
                _rt::string_lift(bytes9)
            };
            V10::Text(e10)
        }
    };
    let result13 = T::main(component::test_package::env::PotRecord {
        id: arg0 as u64,
        name: _rt::string_lift(bytes0),
        active: _rt::bool_lift(arg3 as u8),
        score: arg4,
        opt_tags: match arg5 {
            0 => None,
            1 => {
                let e = {
                    let base4 = arg6;
                    let len4 = arg7;
                    let mut result4 = _rt::Vec::with_capacity(len4);
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e4 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            _rt::string_lift(bytes3)
                        };
                        result4.push(e4);
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    result4
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
        payload: v10,
        validation: match arg12 {
            0 => {
                let e = {
                    let len11 = arg14;
                    let bytes11 = _rt::Vec::from_raw_parts(arg13.cast(), len11, len11);
                    _rt::string_lift(bytes11)
                };
                Ok(e)
            }
            1 => {
                let e = {
                    let len12 = arg14;
                    let bytes12 = _rt::Vec::from_raw_parts(arg13.cast(), len12, len12);
                    _rt::string_lift(bytes12)
                };
                Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    });
    let ptr14 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec15 = (result13.into_bytes()).into_boxed_slice();
    let ptr15 = vec15.as_ptr().cast::<u8>();
    let len15 = vec15.len();
    ::core::mem::forget(vec15);
    *ptr14.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
    *ptr14.add(0).cast::<*mut u8>() = ptr15.cast_mut();
    ptr14
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_main<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn main(p: PotRecord) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : i64, arg1 : * mut u8, arg2 : usize, arg3 : i32, arg4 : f32,
        arg5 : i32, arg6 : * mut u8, arg7 : usize, arg8 : i32, arg9 : * mut u8, arg10 :
        ::core::mem::MaybeUninit::< u64 >, arg11 : usize, arg12 : i32, arg13 : * mut u8,
        arg14 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_main_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8,
        arg9, arg10, arg11, arg12, arg13, arg14) } } #[unsafe (export_name =
        "cabi_post_main")] unsafe extern "C" fn _post_return_main(arg0 : * mut u8,) {
        unsafe { $($path_to_types)*:: __post_return_main::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod test_package {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct SmallRecord {
                pub count: u32,
                pub ratio: f64,
            }
            impl ::core::fmt::Debug for SmallRecord {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("SmallRecord")
                        .field("count", &self.count)
                        .field("ratio", &self.ratio)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum PaymentMethod {
                CreditCard(_rt::String),
                Paypal(_rt::String),
                Cash,
            }
            impl ::core::fmt::Debug for PaymentMethod {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PaymentMethod::CreditCard(e) => {
                            f.debug_tuple("PaymentMethod::CreditCard").field(e).finish()
                        }
                        PaymentMethod::Paypal(e) => {
                            f.debug_tuple("PaymentMethod::Paypal").field(e).finish()
                        }
                        PaymentMethod::Cash => {
                            f.debug_tuple("PaymentMethod::Cash").finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum PotPayload {
                Numbers(_rt::Vec<i64>),
                Small(SmallRecord),
                Payment(PaymentMethod),
                Text(_rt::String),
            }
            impl ::core::fmt::Debug for PotPayload {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PotPayload::Numbers(e) => {
                            f.debug_tuple("PotPayload::Numbers").field(e).finish()
                        }
                        PotPayload::Small(e) => {
                            f.debug_tuple("PotPayload::Small").field(e).finish()
                        }
                        PotPayload::Payment(e) => {
                            f.debug_tuple("PotPayload::Payment").field(e).finish()
                        }
                        PotPayload::Text(e) => {
                            f.debug_tuple("PotPayload::Text").field(e).finish()
                        }
                    }
                }
            }
            /// Small record that exercises WIT types (7 fields including result)
            #[derive(Clone)]
            pub struct PotRecord {
                pub id: u64,
                pub name: _rt::String,
                pub active: bool,
                pub score: f32,
                pub opt_tags: Option<_rt::Vec<_rt::String>>,
                pub payload: PotPayload,
                pub validation: Result<_rt::String, _rt::String>,
            }
            impl ::core::fmt::Debug for PotRecord {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PotRecord")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("active", &self.active)
                        .field("score", &self.score)
                        .field("opt-tags", &self.opt_tags)
                        .field("payload", &self.payload)
                        .field("validation", &self.validation)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn process_pot(input: &PotRecord) -> PotRecord {
                unsafe {
                    let mut cleanup_list = _rt::Vec::new();
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 48 + 8 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 48
                            + 8 * ::core::mem::size_of::<*const u8>()],
                    );
                    let PotRecord {
                        id: id0,
                        name: name0,
                        active: active0,
                        score: score0,
                        opt_tags: opt_tags0,
                        payload: payload0,
                        validation: validation0,
                    } = input;
                    let vec1 = name0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let (result4_0, result4_1, result4_2) = match opt_tags0 {
                        Some(e) => {
                            let vec3 = e;
                            let len3 = vec3.len();
                            let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result3 = if layout3.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout3);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec3.into_iter().enumerate() {
                                let base = result3
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec2 = e;
                                    let ptr2 = vec2.as_ptr().cast::<u8>();
                                    let len2 = vec2.len();
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len2;
                                    *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                                }
                            }
                            cleanup_list.extend_from_slice(&[(result3, layout3)]);
                            (1i32, result3, len3)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let (result11_0, result11_1, result11_2, result11_3) = match payload0 {
                        PotPayload::Numbers(e) => {
                            let vec5 = e;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            (
                                0i32,
                                ptr5.cast_mut(),
                                ::core::mem::MaybeUninit::new(len5 as i64 as u64),
                                0usize,
                            )
                        }
                        PotPayload::Small(e) => {
                            let SmallRecord { count: count6, ratio: ratio6 } = e;
                            (
                                1i32,
                                _rt::as_i32(count6) as *mut u8,
                                ::core::mem::MaybeUninit::new(
                                    (_rt::as_f64(ratio6)).to_bits() as i64 as u64,
                                ),
                                0usize,
                            )
                        }
                        PotPayload::Payment(e) => {
                            let (result9_0, result9_1, result9_2) = match e {
                                PaymentMethod::CreditCard(e) => {
                                    let vec7 = e;
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    (0i32, ptr7.cast_mut(), len7)
                                }
                                PaymentMethod::Paypal(e) => {
                                    let vec8 = e;
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    (1i32, ptr8.cast_mut(), len8)
                                }
                                PaymentMethod::Cash => {
                                    (2i32, ::core::ptr::null_mut(), 0usize)
                                }
                            };
                            (
                                2i32,
                                result9_0 as *mut u8,
                                {
                                    let mut t = ::core::mem::MaybeUninit::<u64>::uninit();
                                    t.as_mut_ptr().cast::<*mut u8>().write(result9_1);
                                    t
                                },
                                result9_2,
                            )
                        }
                        PotPayload::Text(e) => {
                            let vec10 = e;
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            (
                                3i32,
                                ptr10.cast_mut(),
                                ::core::mem::MaybeUninit::new(len10 as i64 as u64),
                                0usize,
                            )
                        }
                    };
                    let (result14_0, result14_1, result14_2) = match validation0 {
                        Ok(e) => {
                            let vec12 = e;
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            (0i32, ptr12.cast_mut(), len12)
                        }
                        Err(e) => {
                            let vec13 = e;
                            let ptr13 = vec13.as_ptr().cast::<u8>();
                            let len13 = vec13.len();
                            (1i32, ptr13.cast_mut(), len13)
                        }
                    };
                    let ptr15 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "component:test-package/env")]
                    unsafe extern "C" {
                        #[link_name = "process-pot"]
                        fn wit_import16(
                            _: i64,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: f32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: ::core::mem::MaybeUninit<u64>,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import16(
                        _: i64,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: f32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: ::core::mem::MaybeUninit<u64>,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import16(
                            _rt::as_i64(id0),
                            ptr1.cast_mut(),
                            len1,
                            match active0 {
                                true => 1,
                                false => 0,
                            },
                            _rt::as_f32(score0),
                            result4_0,
                            result4_1,
                            result4_2,
                            result11_0,
                            result11_1,
                            result11_2,
                            result11_3,
                            result14_0,
                            result14_1,
                            result14_2,
                            ptr15,
                        )
                    };
                    let l17 = *ptr15.add(0).cast::<i64>();
                    let l18 = *ptr15.add(8).cast::<*mut u8>();
                    let l19 = *ptr15
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len20 = l19;
                    let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);
                    let l21 = i32::from(
                        *ptr15
                            .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l22 = *ptr15
                        .add(12 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<f32>();
                    let l23 = i32::from(
                        *ptr15
                            .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l30 = i32::from(
                        *ptr15
                            .add(24 + 4 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let v47 = match l30 {
                        0 => {
                            let e47 = {
                                let l31 = *ptr15
                                    .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l32 = *ptr15
                                    .add(32 + 5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len33 = l32;
                                _rt::Vec::from_raw_parts(l31.cast(), len33, len33)
                            };
                            PotPayload::Numbers(e47)
                        }
                        1 => {
                            let e47 = {
                                let l34 = *ptr15
                                    .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<i32>();
                                let l35 = *ptr15
                                    .add(40 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<f64>();
                                SmallRecord {
                                    count: l34 as u32,
                                    ratio: l35,
                                }
                            };
                            PotPayload::Small(e47)
                        }
                        2 => {
                            let e47 = {
                                let l36 = i32::from(
                                    *ptr15
                                        .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>(),
                                );
                                let v43 = match l36 {
                                    0 => {
                                        let e43 = {
                                            let l37 = *ptr15
                                                .add(32 + 5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l38 = *ptr15
                                                .add(32 + 6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len39 = l38;
                                            let bytes39 = _rt::Vec::from_raw_parts(
                                                l37.cast(),
                                                len39,
                                                len39,
                                            );
                                            _rt::string_lift(bytes39)
                                        };
                                        PaymentMethod::CreditCard(e43)
                                    }
                                    1 => {
                                        let e43 = {
                                            let l40 = *ptr15
                                                .add(32 + 5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l41 = *ptr15
                                                .add(32 + 6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len42 = l41;
                                            let bytes42 = _rt::Vec::from_raw_parts(
                                                l40.cast(),
                                                len42,
                                                len42,
                                            );
                                            _rt::string_lift(bytes42)
                                        };
                                        PaymentMethod::Paypal(e43)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 2, "invalid enum discriminant");
                                        PaymentMethod::Cash
                                    }
                                };
                                v43
                            };
                            PotPayload::Payment(e47)
                        }
                        n => {
                            debug_assert_eq!(n, 3, "invalid enum discriminant");
                            let e47 = {
                                let l44 = *ptr15
                                    .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l45 = *ptr15
                                    .add(32 + 5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len46 = l45;
                                let bytes46 = _rt::Vec::from_raw_parts(
                                    l44.cast(),
                                    len46,
                                    len46,
                                );
                                _rt::string_lift(bytes46)
                            };
                            PotPayload::Text(e47)
                        }
                    };
                    let l48 = i32::from(
                        *ptr15
                            .add(40 + 6 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let result55 = PotRecord {
                        id: l17 as u64,
                        name: _rt::string_lift(bytes20),
                        active: _rt::bool_lift(l21 as u8),
                        score: l22,
                        opt_tags: match l23 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l24 = *ptr15
                                        .add(16 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l25 = *ptr15
                                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base29 = l24;
                                    let len29 = l25;
                                    let mut result29 = _rt::Vec::with_capacity(len29);
                                    for i in 0..len29 {
                                        let base = base29
                                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                        let e29 = {
                                            let l26 = *base.add(0).cast::<*mut u8>();
                                            let l27 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len28 = l27;
                                            let bytes28 = _rt::Vec::from_raw_parts(
                                                l26.cast(),
                                                len28,
                                                len28,
                                            );
                                            _rt::string_lift(bytes28)
                                        };
                                        result29.push(e29);
                                    }
                                    _rt::cabi_dealloc(
                                        base29,
                                        len29 * (2 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    result29
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        payload: v47,
                        validation: match l48 {
                            0 => {
                                let e = {
                                    let l49 = *ptr15
                                        .add(40 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l50 = *ptr15
                                        .add(40 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len51 = l50;
                                    let bytes51 = _rt::Vec::from_raw_parts(
                                        l49.cast(),
                                        len51,
                                        len51,
                                    );
                                    _rt::string_lift(bytes51)
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l52 = *ptr15
                                        .add(40 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l53 = *ptr15
                                        .add(40 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len54 = l53;
                                    let bytes54 = _rt::Vec::from_raw_parts(
                                        l52.cast(),
                                        len54,
                                        len54,
                                    );
                                    _rt::string_lift(bytes54)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    };
                    for (ptr, layout) in cleanup_list {
                        if layout.size() != 0 {
                            _rt::alloc::dealloc(ptr.cast(), layout);
                        }
                    }
                    result55
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:test-package:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 518] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x87\x03\x01A\x02\x01\
A\x06\x01B\x0e\x01r\x02\x05county\x05ratiou\x04\0\x0csmall-record\x03\0\0\x01q\x03\
\x0bcredit-card\x01s\0\x06paypal\x01s\0\x04cash\0\0\x04\0\x0epayment-method\x03\0\
\x02\x01px\x01q\x04\x07numbers\x01\x04\0\x05small\x01\x01\0\x07payment\x01\x03\0\
\x04text\x01s\0\x04\0\x0bpot-payload\x03\0\x05\x01ps\x01k\x07\x01j\x01s\x01s\x01\
r\x07\x02idw\x04names\x06active\x7f\x05scorev\x08opt-tags\x08\x07payload\x06\x0a\
validation\x09\x04\0\x0apot-record\x03\0\x0a\x01@\x01\x05input\x0b\0\x0b\x04\0\x0b\
process-pot\x01\x0c\x03\0\x1acomponent:test-package/env\x05\0\x02\x03\0\0\x0apot\
-record\x03\0\x0apot-record\x03\0\x01\x01@\x01\x01p\x02\0s\x04\0\x04main\x01\x03\
\x04\0\x1fcomponent:test-package/my-world\x04\0\x0b\x0e\x01\0\x08my-world\x03\0\0\
\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bind\
gen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
