// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type UserProfile = component::test_package::env::UserProfile;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<i64>();
    let l1 = *arg0.add(8).cast::<*mut u8>();
    let l2 = *arg0.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len3 = l2;
    let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
    let l4 = *arg0.add(8 + 2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l5 = *arg0.add(8 + 3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len6 = l5;
    let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
    let l7 = *arg0.add(8 + 4 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l8 = *arg0.add(8 + 5 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len9 = l8;
    let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
    let l10 = *arg0.add(8 + 6 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l11 = *arg0.add(8 + 7 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len12 = l11;
    let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);
    let l13 = *arg0.add(8 + 8 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l14 = *arg0.add(8 + 9 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l15 = *arg0.add(8 + 10 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len16 = l15;
    let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
    let l17 = *arg0.add(8 + 11 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l18 = *arg0.add(8 + 12 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len19 = l18;
    let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);
    let l20 = i32::from(
        *arg0.add(8 + 13 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l21 = *arg0.add(8 + 14 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l22 = *arg0.add(8 + 15 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len23 = l22;
    let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);
    let l24 = *arg0.add(8 + 16 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l25 = *arg0.add(8 + 17 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len26 = l25;
    let bytes26 = _rt::Vec::from_raw_parts(l24.cast(), len26, len26);
    let l27 = *arg0.add(8 + 18 * ::core::mem::size_of::<*const u8>()).cast::<f64>();
    let l28 = *arg0.add(16 + 18 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l29 = *arg0.add(16 + 19 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l30 = *arg0.add(16 + 20 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len31 = l30;
    let bytes31 = _rt::Vec::from_raw_parts(l29.cast(), len31, len31);
    let l32 = *arg0.add(24 + 20 * ::core::mem::size_of::<*const u8>()).cast::<i64>();
    let l33 = *arg0.add(32 + 20 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l34 = *arg0.add(32 + 21 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len35 = l34;
    let bytes35 = _rt::Vec::from_raw_parts(l33.cast(), len35, len35);
    let l36 = *arg0.add(32 + 22 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l37 = *arg0.add(32 + 23 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base41 = l36;
    let len41 = l37;
    let mut result41 = _rt::Vec::with_capacity(len41);
    for i in 0..len41 {
        let base = base41.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        let e41 = {
            let l38 = *base.add(0).cast::<*mut u8>();
            let l39 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len40 = l39;
            let bytes40 = _rt::Vec::from_raw_parts(l38.cast(), len40, len40);
            _rt::string_lift(bytes40)
        };
        result41.push(e41);
    }
    _rt::cabi_dealloc(
        base41,
        len41 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let l42 = *arg0.add(32 + 24 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l43 = *arg0.add(32 + 25 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len44 = l43;
    let l45 = *arg0.add(32 + 26 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l46 = *arg0.add(32 + 27 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base50 = l45;
    let len50 = l46;
    let mut result50 = _rt::Vec::with_capacity(len50);
    for i in 0..len50 {
        let base = base50.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        let e50 = {
            let l47 = *base.add(0).cast::<*mut u8>();
            let l48 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len49 = l48;
            let bytes49 = _rt::Vec::from_raw_parts(l47.cast(), len49, len49);
            _rt::string_lift(bytes49)
        };
        result50.push(e50);
    }
    _rt::cabi_dealloc(
        base50,
        len50 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result51 = T::main(component::test_package::env::UserProfile {
        id: l0 as u64,
        username: _rt::string_lift(bytes3),
        email: _rt::string_lift(bytes6),
        first_name: _rt::string_lift(bytes9),
        last_name: _rt::string_lift(bytes12),
        age: l13 as u32,
        country: _rt::string_lift(bytes16),
        city: _rt::string_lift(bytes19),
        is_verified: _rt::bool_lift(l20 as u8),
        postal_code: _rt::string_lift(bytes23),
        phone: _rt::string_lift(bytes26),
        account_balance: l27,
        loyalty_points: l28 as u32,
        subscription_tier: _rt::string_lift(bytes31),
        last_login_timestamp: l32 as u64,
        registration_date: _rt::string_lift(bytes35),
        tags: result41,
        purchase_history: _rt::Vec::from_raw_parts(l42.cast(), len44, len44),
        preferences: result50,
    });
    _rt::cabi_dealloc(arg0, 32 + 28 * ::core::mem::size_of::<*const u8>(), 8);
    let ptr52 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec53 = (result51.into_bytes()).into_boxed_slice();
    let ptr53 = vec53.as_ptr().cast::<u8>();
    let len53 = vec53.len();
    ::core::mem::forget(vec53);
    *ptr52.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len53;
    *ptr52.add(0).cast::<*mut u8>() = ptr53.cast_mut();
    ptr52
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_main<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn main(profile: UserProfile) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_main_cabi::<$ty > (arg0) } } #[unsafe (export_name = "cabi_post_main")]
        unsafe extern "C" fn _post_return_main(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_main::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod test_package {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct UserProfile {
                pub id: u64,
                pub username: _rt::String,
                pub email: _rt::String,
                pub first_name: _rt::String,
                pub last_name: _rt::String,
                pub age: u32,
                pub country: _rt::String,
                pub city: _rt::String,
                pub is_verified: bool,
                pub postal_code: _rt::String,
                pub phone: _rt::String,
                pub account_balance: f64,
                pub loyalty_points: u32,
                pub subscription_tier: _rt::String,
                pub last_login_timestamp: u64,
                pub registration_date: _rt::String,
                pub tags: _rt::Vec<_rt::String>,
                pub purchase_history: _rt::Vec<u64>,
                pub preferences: _rt::Vec<_rt::String>,
            }
            impl ::core::fmt::Debug for UserProfile {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("UserProfile")
                        .field("id", &self.id)
                        .field("username", &self.username)
                        .field("email", &self.email)
                        .field("first-name", &self.first_name)
                        .field("last-name", &self.last_name)
                        .field("age", &self.age)
                        .field("country", &self.country)
                        .field("city", &self.city)
                        .field("is-verified", &self.is_verified)
                        .field("postal-code", &self.postal_code)
                        .field("phone", &self.phone)
                        .field("account-balance", &self.account_balance)
                        .field("loyalty-points", &self.loyalty_points)
                        .field("subscription-tier", &self.subscription_tier)
                        .field("last-login-timestamp", &self.last_login_timestamp)
                        .field("registration-date", &self.registration_date)
                        .field("tags", &self.tags)
                        .field("purchase-history", &self.purchase_history)
                        .field("preferences", &self.preferences)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn process_profile(profile: &UserProfile) -> UserProfile {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 32 + 28 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 32
                            + 28 * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    let UserProfile {
                        id: id1,
                        username: username1,
                        email: email1,
                        first_name: first_name1,
                        last_name: last_name1,
                        age: age1,
                        country: country1,
                        city: city1,
                        is_verified: is_verified1,
                        postal_code: postal_code1,
                        phone: phone1,
                        account_balance: account_balance1,
                        loyalty_points: loyalty_points1,
                        subscription_tier: subscription_tier1,
                        last_login_timestamp: last_login_timestamp1,
                        registration_date: registration_date1,
                        tags: tags1,
                        purchase_history: purchase_history1,
                        preferences: preferences1,
                    } = profile;
                    *ptr0.add(0).cast::<i64>() = _rt::as_i64(id1);
                    let vec2 = username1;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    *ptr0
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len2;
                    *ptr0.add(8).cast::<*mut u8>() = ptr2.cast_mut();
                    let vec3 = email1;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    *ptr0
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len3;
                    *ptr0
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = first_name1;
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    *ptr0
                        .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len4;
                    *ptr0
                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = last_name1;
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    *ptr0
                        .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len5;
                    *ptr0
                        .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    *ptr0
                        .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(age1);
                    let vec6 = country1;
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    *ptr0
                        .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len6;
                    *ptr0
                        .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = city1;
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    *ptr0
                        .add(8 + 12 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len7;
                    *ptr0
                        .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                    *ptr0
                        .add(8 + 13 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match is_verified1 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    let vec8 = postal_code1;
                    let ptr8 = vec8.as_ptr().cast::<u8>();
                    let len8 = vec8.len();
                    *ptr0
                        .add(8 + 15 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len8;
                    *ptr0
                        .add(8 + 14 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr8.cast_mut();
                    let vec9 = phone1;
                    let ptr9 = vec9.as_ptr().cast::<u8>();
                    let len9 = vec9.len();
                    *ptr0
                        .add(8 + 17 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len9;
                    *ptr0
                        .add(8 + 16 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr9.cast_mut();
                    *ptr0
                        .add(8 + 18 * ::core::mem::size_of::<*const u8>())
                        .cast::<f64>() = _rt::as_f64(account_balance1);
                    *ptr0
                        .add(16 + 18 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(loyalty_points1);
                    let vec10 = subscription_tier1;
                    let ptr10 = vec10.as_ptr().cast::<u8>();
                    let len10 = vec10.len();
                    *ptr0
                        .add(16 + 20 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len10;
                    *ptr0
                        .add(16 + 19 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr10.cast_mut();
                    *ptr0
                        .add(24 + 20 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>() = _rt::as_i64(last_login_timestamp1);
                    let vec11 = registration_date1;
                    let ptr11 = vec11.as_ptr().cast::<u8>();
                    let len11 = vec11.len();
                    *ptr0
                        .add(32 + 21 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len11;
                    *ptr0
                        .add(32 + 20 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr11.cast_mut();
                    let vec13 = tags1;
                    let len13 = vec13.len();
                    let layout13 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec13.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result13 = if layout13.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout13).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout13);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec13.into_iter().enumerate() {
                        let base = result13
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec12 = e;
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
                        }
                    }
                    *ptr0
                        .add(32 + 23 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len13;
                    *ptr0
                        .add(32 + 22 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result13;
                    let vec14 = purchase_history1;
                    let ptr14 = vec14.as_ptr().cast::<u8>();
                    let len14 = vec14.len();
                    *ptr0
                        .add(32 + 25 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len14;
                    *ptr0
                        .add(32 + 24 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr14.cast_mut();
                    let vec16 = preferences1;
                    let len16 = vec16.len();
                    let layout16 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec16.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result16 = if layout16.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout16).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout16);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec16.into_iter().enumerate() {
                        let base = result16
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec15 = e;
                            let ptr15 = vec15.as_ptr().cast::<u8>();
                            let len15 = vec15.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len15;
                            *base.add(0).cast::<*mut u8>() = ptr15.cast_mut();
                        }
                    }
                    *ptr0
                        .add(32 + 27 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len16;
                    *ptr0
                        .add(32 + 26 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result16;
                    let ptr17 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "component:test-package/env")]
                    unsafe extern "C" {
                        #[link_name = "process-profile"]
                        fn wit_import18(_: *mut u8, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import18(_: *mut u8, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import18(ptr0, ptr17) };
                    let l19 = *ptr17.add(0).cast::<i64>();
                    let l20 = *ptr17.add(8).cast::<*mut u8>();
                    let l21 = *ptr17
                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len22 = l21;
                    let bytes22 = _rt::Vec::from_raw_parts(l20.cast(), len22, len22);
                    let l23 = *ptr17
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l24 = *ptr17
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len25 = l24;
                    let bytes25 = _rt::Vec::from_raw_parts(l23.cast(), len25, len25);
                    let l26 = *ptr17
                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l27 = *ptr17
                        .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len28 = l27;
                    let bytes28 = _rt::Vec::from_raw_parts(l26.cast(), len28, len28);
                    let l29 = *ptr17
                        .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l30 = *ptr17
                        .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len31 = l30;
                    let bytes31 = _rt::Vec::from_raw_parts(l29.cast(), len31, len31);
                    let l32 = *ptr17
                        .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>();
                    let l33 = *ptr17
                        .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l34 = *ptr17
                        .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len35 = l34;
                    let bytes35 = _rt::Vec::from_raw_parts(l33.cast(), len35, len35);
                    let l36 = *ptr17
                        .add(8 + 11 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l37 = *ptr17
                        .add(8 + 12 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len38 = l37;
                    let bytes38 = _rt::Vec::from_raw_parts(l36.cast(), len38, len38);
                    let l39 = i32::from(
                        *ptr17
                            .add(8 + 13 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l40 = *ptr17
                        .add(8 + 14 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l41 = *ptr17
                        .add(8 + 15 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len42 = l41;
                    let bytes42 = _rt::Vec::from_raw_parts(l40.cast(), len42, len42);
                    let l43 = *ptr17
                        .add(8 + 16 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l44 = *ptr17
                        .add(8 + 17 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len45 = l44;
                    let bytes45 = _rt::Vec::from_raw_parts(l43.cast(), len45, len45);
                    let l46 = *ptr17
                        .add(8 + 18 * ::core::mem::size_of::<*const u8>())
                        .cast::<f64>();
                    let l47 = *ptr17
                        .add(16 + 18 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>();
                    let l48 = *ptr17
                        .add(16 + 19 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l49 = *ptr17
                        .add(16 + 20 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len50 = l49;
                    let bytes50 = _rt::Vec::from_raw_parts(l48.cast(), len50, len50);
                    let l51 = *ptr17
                        .add(24 + 20 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let l52 = *ptr17
                        .add(32 + 20 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l53 = *ptr17
                        .add(32 + 21 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len54 = l53;
                    let bytes54 = _rt::Vec::from_raw_parts(l52.cast(), len54, len54);
                    let l55 = *ptr17
                        .add(32 + 22 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l56 = *ptr17
                        .add(32 + 23 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base60 = l55;
                    let len60 = l56;
                    let mut result60 = _rt::Vec::with_capacity(len60);
                    for i in 0..len60 {
                        let base = base60
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e60 = {
                            let l57 = *base.add(0).cast::<*mut u8>();
                            let l58 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len59 = l58;
                            let bytes59 = _rt::Vec::from_raw_parts(
                                l57.cast(),
                                len59,
                                len59,
                            );
                            _rt::string_lift(bytes59)
                        };
                        result60.push(e60);
                    }
                    _rt::cabi_dealloc(
                        base60,
                        len60 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l61 = *ptr17
                        .add(32 + 24 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l62 = *ptr17
                        .add(32 + 25 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len63 = l62;
                    let l64 = *ptr17
                        .add(32 + 26 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l65 = *ptr17
                        .add(32 + 27 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base69 = l64;
                    let len69 = l65;
                    let mut result69 = _rt::Vec::with_capacity(len69);
                    for i in 0..len69 {
                        let base = base69
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e69 = {
                            let l66 = *base.add(0).cast::<*mut u8>();
                            let l67 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len68 = l67;
                            let bytes68 = _rt::Vec::from_raw_parts(
                                l66.cast(),
                                len68,
                                len68,
                            );
                            _rt::string_lift(bytes68)
                        };
                        result69.push(e69);
                    }
                    _rt::cabi_dealloc(
                        base69,
                        len69 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result70 = UserProfile {
                        id: l19 as u64,
                        username: _rt::string_lift(bytes22),
                        email: _rt::string_lift(bytes25),
                        first_name: _rt::string_lift(bytes28),
                        last_name: _rt::string_lift(bytes31),
                        age: l32 as u32,
                        country: _rt::string_lift(bytes35),
                        city: _rt::string_lift(bytes38),
                        is_verified: _rt::bool_lift(l39 as u8),
                        postal_code: _rt::string_lift(bytes42),
                        phone: _rt::string_lift(bytes45),
                        account_balance: l46,
                        loyalty_points: l47 as u32,
                        subscription_tier: _rt::string_lift(bytes50),
                        last_login_timestamp: l51 as u64,
                        registration_date: _rt::string_lift(bytes54),
                        tags: result60,
                        purchase_history: _rt::Vec::from_raw_parts(
                            l61.cast(),
                            len63,
                            len63,
                        ),
                        preferences: result69,
                    };
                    if layout13.size() != 0 {
                        _rt::alloc::dealloc(result13.cast(), layout13);
                    }
                    if layout16.size() != 0 {
                        _rt::alloc::dealloc(result16.cast(), layout16);
                    }
                    result70
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:test-package:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 549] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa6\x03\x01A\x02\x01\
A\x06\x01B\x06\x01ps\x01pw\x01r\x13\x02idw\x08usernames\x05emails\x0afirst-names\
\x09last-names\x03agey\x07countrys\x04citys\x0bis-verified\x7f\x0bpostal-codes\x05\
phones\x0faccount-balanceu\x0eloyalty-pointsy\x11subscription-tiers\x14last-logi\
n-timestampw\x11registration-dates\x04tags\0\x10purchase-history\x01\x0bpreferen\
ces\0\x04\0\x0cuser-profile\x03\0\x02\x01@\x01\x07profile\x03\0\x03\x04\0\x0fpro\
cess-profile\x01\x04\x03\0\x1acomponent:test-package/env\x05\0\x02\x03\0\0\x0cus\
er-profile\x03\0\x0cuser-profile\x03\0\x01\x01@\x01\x07profile\x02\0s\x04\0\x04m\
ain\x01\x03\x04\0\x1fcomponent:test-package/my-world\x04\0\x0b\x0e\x01\0\x08my-w\
orld\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\
\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
